param(
    # When set, this overrides the auto-derived YYYY.M.D.N-XXXX stamp. The Release workflow
    # passes the git tag here (with the leading "v" stripped) so the published release's tag,
    # zip filename, and embedded version are all the same string. Local builds leave this
    # empty and get the auto-derived stamp from $Today + $BuildCount + a fresh GUID prefix.
    [string]$Version = "",

    # Skip the release zip packaging step. CI builds always want it; local rebuilds usually
    # don't, and accumulate one zip per build in release/ otherwise.
    [switch]$SkipZip,

    # Skip the CMake configure step (rerun MSBuild only). Useful when iterating on a single
    # source file -- saves the ~10s reconfigure. The CMake configure runs unconditionally
    # without this flag because that's the safe default; missed reconfigures cause stale
    # build files to mask source changes.
    [switch]$SkipConfigure
)

$ErrorActionPreference = "Stop"

# Pin the working directory to the script's own root.
Set-Location $PSScriptRoot

# Activate the repo's tracked git hooks (.githooks/) the first time the build runs in a clone.
try {
    $current = (& git config --local --get core.hooksPath 2>$null)
    if ($LASTEXITCODE -eq 0 -and $current -ne ".githooks") {
        & git config --local core.hooksPath .githooks
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Configured local git core.hooksPath = .githooks (commit-msg guard now active)." -ForegroundColor DarkGray
        }
    } elseif ($LASTEXITCODE -ne 0) {
        & git config --local core.hooksPath .githooks 2>$null
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Configured local git core.hooksPath = .githooks (commit-msg guard now active)." -ForegroundColor DarkGray
        }
    }
} catch { }

# --- Submodule check ---
$openvrHeader = Join-Path $PSScriptRoot "lib/openvr/headers/openvr_driver.h"
if (!(Test-Path $openvrHeader)) {
    Write-Host "Submodules missing -- running 'git submodule update --init --recursive'..." -ForegroundColor Yellow
    $PrevEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        & git submodule update --init --recursive
        if ($LASTEXITCODE -ne 0) {
            throw "Submodule init failed (exit $LASTEXITCODE). Inspect the output above."
        }
    } finally {
        $ErrorActionPreference = $PrevEap
    }
}

# --- Daily Versioning Logic ---
$LocalVersionState = Join-Path $PSScriptRoot "build/local_build_state.json"
$BuildStateDir = Split-Path $LocalVersionState -Parent
if (!(Test-Path $BuildStateDir)) { New-Item -ItemType Directory -Path $BuildStateDir -Force | Out-Null }

if ($Version) {
    if ($Version -notmatch '^\d{4}\.\d+\.\d+\.\d+(-[A-Fa-f0-9]{4})?$') {
        throw "Invalid -Version '$Version'. Expected YYYY.M.D.N (release) or YYYY.M.D.N-XXXX (dev, XXXX = 4 hex chars)."
    }
    $FullVersion = $Version
    Write-Host "Using caller-supplied version (skipping local-state increment)." -ForegroundColor DarkGray
} else {
    $Today = Get-Date -Format "yyyy.M.d"
    $BuildCount = 0
    $UID = [Guid]::NewGuid().ToString().Substring(0, 4).ToUpper()

    if (Test-Path $LocalVersionState) {
        $State = Get-Content $LocalVersionState | ConvertFrom-Json
        if ($State.Date -eq $Today) {
            $BuildCount = $State.Count + 1
        }
    }

    $FullVersion = "$Today.$BuildCount-$UID"
    @{ "Date" = $Today; "Count" = $BuildCount } | ConvertTo-Json | Out-File $LocalVersionState -Encoding UTF8
}

Write-Host "Building Version: $FullVersion" -ForegroundColor Magenta

# Emit version.txt at the repo root. The git prepare-commit-msg hook reads this to stamp commits.
$FullVersion | Set-Content -Path (Join-Path $PSScriptRoot "version.txt") -Encoding UTF8 -NoNewline

# Emit src/overlay/BuildStamp.h so the UI footer can display the live build stamp. The
# header is regenerated each build; gitignored.
$BuildStampPath = Join-Path $PSScriptRoot "src/overlay/BuildStamp.h"
$BuildChannel = if ($Version) { "release" } else { "dev" }
$BuildStampContent = @"
// This file is generated by build.ps1. Do not edit; do not commit.
#pragma once

#define FINGERSMOOTH_BUILD_STAMP "$FullVersion"
#define FINGERSMOOTH_BUILD_CHANNEL "$BuildChannel"
"@
Set-Content -Path $BuildStampPath -Value $BuildStampContent -Encoding UTF8

# --- CMake configure ---
if (-not $SkipConfigure) {
    Write-Host "`n--- CMake configure ---" -ForegroundColor Cyan
    $PrevEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        & cmake -G "Visual Studio 17 2022" -A x64 -B bin -S . "-DCMAKE_POLICY_VERSION_MINIMUM=3.5" -Wno-dev
        if ($LASTEXITCODE -ne 0) { throw "cmake configure failed (exit $LASTEXITCODE)" }
    } finally {
        $ErrorActionPreference = $PrevEap
    }
}

# --- MSBuild ---
Write-Host "`n--- Building (Release|x64) ---" -ForegroundColor Cyan
$PrevEap = $ErrorActionPreference
$ErrorActionPreference = "Continue"
try {
    & cmake --build bin --config Release --parallel
    if ($LASTEXITCODE -ne 0) { throw "cmake build failed (exit $LASTEXITCODE)" }
} finally {
    $ErrorActionPreference = $PrevEap
}

# --- Locate built artifacts ---
$OverlayExe = Join-Path $PSScriptRoot "bin/artifacts/Release/FingerSmoothing.exe"
$DriverDir  = Join-Path $PSScriptRoot "bin/driver_01fingersmoothing"
$DriverDll  = Join-Path $DriverDir "bin/win64/driver_01fingersmoothing.dll"

if (!(Test-Path $OverlayExe)) { throw "Expected overlay exe not found at $OverlayExe" }
if (!(Test-Path $DriverDll))  { throw "Expected driver DLL not found at $DriverDll" }

# --- Release zip ---
if ($SkipZip) {
    Write-Host "`nSkipping release zip (-SkipZip)." -ForegroundColor DarkGray
} else {
    Write-Host "`n--- Packaging release zip ---" -ForegroundColor Cyan

    $ReleaseDir = Join-Path $PSScriptRoot "release"
    if (!(Test-Path $ReleaseDir)) { New-Item -ItemType Directory -Path $ReleaseDir -Force | Out-Null }

    $StageDir = Join-Path $ReleaseDir "_stage_$FullVersion"
    if (Test-Path $StageDir) { Remove-Item -Recurse -Force $StageDir }
    New-Item -ItemType Directory -Path $StageDir -Force | Out-Null

    Copy-Item -Path $OverlayExe -Destination $StageDir
    Copy-Item -Path $DriverDir -Destination $StageDir -Recurse
    $FullVersion | Set-Content -Path (Join-Path $StageDir "version.txt") -Encoding UTF8 -NoNewline

    $ZipPath = Join-Path $ReleaseDir "FingerSmoothing-$FullVersion.zip"
    if (Test-Path $ZipPath) { Remove-Item -Force $ZipPath }
    Compress-Archive -Path (Join-Path $StageDir "*") -DestinationPath $ZipPath -Force
    Remove-Item -Recurse -Force $StageDir

    $ZipHash = (Get-FileHash $ZipPath -Algorithm SHA256).Hash
    Write-Host "Release zip ready: $ZipPath" -ForegroundColor Green
    Write-Host "SHA256: $ZipHash" -ForegroundColor Green
}

Write-Host "`nBuild $FullVersion complete." -ForegroundColor Green
Write-Host "  Overlay: $OverlayExe" -ForegroundColor DarkGray
Write-Host "  Driver:  $DriverDll"  -ForegroundColor DarkGray
