#pragma once

// Marketing / SDK-style version. The per-build YYYY.M.D.N-XXXX stamp lives in
// BuildStamp.h (generated by build.ps1) and is what we display in the UI footer
// and stamp into git commits. This is the slower-moving "1.x" number.
#define FINGERSMOOTH_VERSION_STRING "0.1.0"
